### ISSUE TITLE
Expired invitation

### ISSUE THREAD

**Issue by akowalska622** [javascript-tutorial/pl.javascript.info#117]
My invitation has expired (https://github.com/javascript-tutorial/pl.javascript.info/issues/1#issuecomment-962179778), because I've missed the mail and it was due to 7 days.

After visiting https://github.com/javascript-tutorial/pl.javascript.info/invitations I get a notification: "Sorry, we couldn't find that repository invitation. It is possible that the invitation was revoked or that you are not logged into the invited account."
<img width="1436" alt="Zrzut ekranu 2021-11-5 o 21 05 10" src="https://user-images.githubusercontent.com/63072419/140571882-c5d50a38-64ae-4f22-b2e8-a298b71f0fa3.png">

And the mail with invitations says that I need to accept it within 7 days.

Could you re-send the invitation please? :)

**Comment by akowalska622** [comment]
@iliakan

**Comment by iliakan** [comment]
Please check now?

**Comment by iliakan** [comment]
You've been invited to join the team, not exactly the repo.

**Comment by akowalska622** [comment]
Works perfectly now! Thanks 💚

**Comment by iliakan** [comment]
Great! Please mention me in case of any questions!
